spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  docker:
    compose:
      enabled: false
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
      username: REST_API_APP
      password: pass
      driver-class-name: oracle.jdbc.OracleDriver
