spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: REST_API
        format_sql: true
  docker:
    compose:
      enabled: false
  liquibase:
    change-log: classpath:/db/changelog/dbchangelog.yaml
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    user: REST_API_APP
    password: pass
    default-schema: REST_API
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: REST_API_APP
    password: pass
    driver-class-name: oracle.jdbc.OracleDriver
