ALTER
SESSION
SET CONTAINER = FREEPDB1;
CREATE TABLESPACE REST_API DATAFILE 'rest_api.dbf'
    SIZE 10m;

ALTER USER REST_API quota unlimited on REST_API;
CREATE USER REST_API_APP identified by pass default tablespace REST_API;

ALTER USER REST_API_APP quota unlimited on REST_API;
GRANT CONNECT, RESOURCE, DBA TO REST_API_APP;
GRANT UNLIMITED TABLESPACE TO REST_API_APP;
GRANT UNLIMITED TABLESPACE TO REST_API;