services:
  oracle:
    container_name: rest-api
    image: 'gvenzl/oracle-free:latest'
    ports:
      - '1521:1521'
    volumes:
      - ./oracle:/docker-entrypoint-initdb.d/
      - ./db-data/rest-api:/opt/oracle/oradata
    environment:
      ORACLE_PASSWORD: systempass
      ORACLE_DATABASE: REST_API
      APP_USER: REST_API
      APP_USER_PASSWORD: pass
      TARGET_PDB: REST_API
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      retries: 10
      timeout: 5s
